### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by kamilwlf** [RomanIakovlev/timeshape#1]
`TimeZoneEngine.initialize().query(52.52, 13.40);`
result:

> java.lang.OutOfMemoryError: Java heap space
> 
> 	at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2041)
> 	at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
> 	at java.lang.Double.parseDouble(Double.java:538)
> 	at com.fasterxml.jackson.core.io.NumberInput.parseDouble(NumberInput.java:285)
> 	at com.fasterxml.jackson.core.util.TextBuffer.contentsAsDouble(TextBuffer.java:399)
> 	at com.fasterxml.jackson.core.base.ParserBase._parseSlowFloat(ParserBase.java:886)
> 	at com.fasterxml.jackson.core.base.ParserBase._parseNumericValue(ParserBase.java:834)
> 	at com.fasterxml.jackson.core.base.ParserBase.getDoubleValue(ParserBase.java:751)
> 	at org.geojson.jackson.LngLatAltDeserializer.extractDouble(LngLatAltDeserializer.java:68)
> 	at org.geojson.jackson.LngLatAltDeserializer.deserializeArray(LngLatAltDeserializer.java:30)
> 	at org.geojson.jackson.LngLatAltDeserializer.deserialize(LngLatAltDeserializer.java:22)
> 	at org.geojson.jackson.LngLatAltDeserializer.deserialize(LngLatAltDeserializer.java:16)
> 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:287)
> 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
> 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
> 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:287)
> 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259)
> 	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26)
> 	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504)
> 	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:104)
> 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
> 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:178)
> 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:150)
> 	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:129)
> 	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer.deserializeTypedFromObject(AsPropertyTypeDeserializer.java:97)
> 	at com.fasterxml.jackson.databind.deser.AbstractDeserializer.deserializeWithType(AbstractDeserializer.java:142)
> 	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:502)
> 	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:104)
> 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276)
> 	at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:178)
> 	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:150)
> 	at com.fasterxml.jackson.databind.jsontype.impl.AsPropertyTypeDeserializer._deserializeTypedForId(AsPropertyTypeDeserializer.java:129)
> 
> *** java.lang.instrument ASSERTION FAILED ***: "!errorOutstanding" with message can't create name string at JPLISAgent.c line: 807

**Comment by RomanIakovlev** [comment]
Looks like your JVM is running out of memory when loading the data. What's the JVM heap memory setting that you use?

**Comment by RomanIakovlev** [comment]
I've tested this a bit further, and it seems 512 megabytes of heap space (i.e. `-Xmx512m` java option) should suffice to build an index and run the code above without out of memory error. I'll update the readme with this info. Thanks @kamilwlf for bringing this up!

**Comment by RomanIakovlev** [comment]
@kamilwlf could you please confirm increasing the maximum heap memory has resolved your problem?

**Comment by kamilwlf** [comment]
@RomanIakovlev Thank you for taking the trouble to find the cause. Unfortunately I cant change heap space on server.  I found a different solution.

**Comment by RomanIakovlev** [comment]
I've released the version `2018d.2` that reduces heap memory usage from 512m to 174m, i.e. almost 3 times. Hopefully this makes `timeshape` useful in more scenarios! I'm closing the issue now.
