### ISSUE TITLE
Which algorithm used to find Time zone id?

### ISSUE THREAD

**Issue by iknow34languages** [RomanIakovlev/timeshape#11]
@RomanIakovlev 
Can you help to explain which algorithm used in the project ?

i find that it should use huge memory to initial  all map from lat (90 to -90) Long(-180 to 180);

But i want to reduce it's memory cost  and speed the look up time spend;

Thanks;

**Comment by RomanIakovlev** [comment]
@iknow34languages I've updated the readme file with the description of which algorithm is used to query the time zones data, which hopefully answers your question. The readme also contains information on how to reduce the memory usage of the library, by limiting the amount of time zones loaded. I'm closing this issue now, but feel free to open a new one if you want to continue the discussion.
