### ISSUE TITLE
No timezone for some places in Mexico for 2022g.16

### ISSUE THREAD

**Issue by michaeldiener** [RomanIakovlev/timeshape#114]
Hi,

with the latest release there is no timezone returned for e.g. 31.752,-106.457 or 31.038,-107.045. Both places are in Chihuahua and I haven't seen an issue (yet?) for other places.
It works fine for 2022f.15.

For completeness, the code looks similar to this:
`TimeZoneEngine.initialize().queryAll(lat, lon)`

Thanks, Michael

**Comment by michaeldiener** [comment]
Thanks, you pointed me in the right direction. I actually do use the latest Java 17 version (Oracle 17.0.6+9-LTS-190), but it doesn't have the latest timezone data. But there is a timezone updater tool from Oracle that adds support for America/Ciudad_Juarez.

If anybody else has the same problem, you can find the tool here: https://www.oracle.com/java/technologies/javase-tzupdater-downloads.html
Unzip and execute (you might have to sudo):
`java -jar tzupdater-2.3.2/tzupdater.jar -l https://www.iana.org/time-zones/repository/tzdata-latest.tar.gz -v`

Thanks again, problem solved!

**Comment by RomanIakovlev** [comment]
Happy to hear this is resolved! Also good point about the `tzupdater` tool, I wonder if it would make sense to put this to readme?

**Comment by michaeldiener** [comment]
I think it would make sense, but then only for Oracle JREs and JDKs.
