### ISSUE TITLE
Add the ability to serialize and deserialize TimeZoneEngine class.

### ISSUE THREAD

**Issue by PhotoKevin** [RomanIakovlev/timeshape#140]
TimeZoneEngine.initialize () can take a significant amount of time to run on an Android phone. Upwards of 20 seconds on a Moto G Play as an example. Loading a smaller region doesn't help as it appears that the bottleneck is reading the compressed data file.

Once the data has been loaded, however, it would be possible to use serialization to save only the loaded zones to the app's cache area. Subsequent runs could load the serialized data with a substantial performance gain. Experiments show that the same Moto G Play can typically load all of of the zones used by Northern America in under a second.

Pseudo code showing initialization via deserialization
```
File f = ... // Something like TZ_MyRegion.cache in the app cache directory.
if (f.exists())
   engine = deserializeTimeZoneEngine (f); // Exception processing not shown here.
if (engine == null) 
{
   engine = TimeZoneEngine.initialize (...) // Bounding box supplied from user preferences. 
   serializeTimeZoneEngine (f, engine); // Saved for next time the app runs.
}

public void serializeTimeZoneEngine (File f, TimeZoneEngine eng) throws IOException
{
    FileOutputStream fileOutputStream = new FileOutputStream (f, false);
    try (ObjectOutputStream objectOutputStream = new ObjectOutputStream (new BufferedOutputStream (fileOutputStream))) {
       objectOutputStream.writeObject (eng);
       objectOutputStream.flush ();
    }
}

public static TimeZoneEngine deserializeTimeZoneEngine (File f) throws IOException, ClassNotFoundException
{
    FileInputStream fileInputStream = new FileInputStream(f);
    try (ObjectInputStream objectInputStream = new ObjectInputStream(fileInputStream)) {
        return (TimeZoneEngine) objectInputStream.readObject ();
    }
}

```
When implemented like this, the first run of an app will take the full time to initialize TimeZoneEngine, but subsequent runs will be almost immediate. The app is responsible for deciding how to allow the user to select the region of interest and to force a reinitialization and serialization if they change regions. 

Cached data sizes:
Northern America (Include Hawaii) ~9MB
All zones ~120MB.

**Comment by RomanIakovlev** [comment]
I think it makes sense to add serialization support to Timeshape classes, but the other mechanisms (like reading and writing cached files, etc.) probably don't belong in the library itself, because they might be platform specific (e.g. look different on Android phone than on some backend service). 

What kind of minimum addition could we make to the library itself here, which is applicable to all of these different usage scenarios? Just mark the classes as serializable maybe, or is there something else?

**Comment by PhotoKevin** [comment]
Working with a File object is pretty close to the minimum. It's certainly bog standard java calls.  The caller would have to create the File object eliminating any concerns about platforms. Could it work to just add "implements Serializable" and have the caller do the writeObject/readObject calls (something has to do them)? Probably. Let me give that a try.

**Comment by PhotoKevin** [comment]
The more I think about it, yes. I could put to/from File in as part of the unit test. That would give people a handy example. 

That's different enough from this writeup that this issue should probably be dumped an a new one made.

**Comment by RomanIakovlev** [comment]
Yeah I think we should try to keep the changes to the necessary minimum. Timeshape is a library, not a framework, and I try to keep it as un-opinionated as possible. Even the choice of `java.io` vs `java.nio` is best to avoid. 

I I like your idea of making a test to illustrate how certain feature must be used, and I agree that it looks like the best approach here would be to just mark the necessary classes as serializable.

No need to create separate issue for this, it's fine to use this one, maybe just edit the first post to add the conclusion we've reached, for clarity.

**Comment by PhotoKevin** [comment]
Issue has been edited.
My changes are in this fork: https://github.com/PhotoKevin/timeshape


There is a pre-existing issue with the build process on Windows. After an initial clone, sbt compile gives these errors.
[info] Timeshape resource doesn't exist in this host, creating it now.
[info] Downloading timezone data with version: 2024a
[info] running D:\projects\timeshapeFork\builder\target\universal\stage/bin/timeshape-builder 2024a D:\projects\timeshapeFork\core\target\resource_managed\main\data.tar.zstd
[error] java.io.IOException: Cannot run program "D:\projects\timeshapeFork\builder\target\universal\stage/bin/timeshape-builder": CreateProcess error=193, %1 is not a valid Win32 application

Copying the "running..." part and executing that from a command prompt works, and once the data.tar.zstd has been built things are happy from then on.

**Comment by RomanIakovlev** [comment]
Thanks! Please create a pull request so that we can do a proper code review.

**Comment by SavtechSolutions** [comment]
I see this was already merged; when will it be released? We're also eagerly awaiting this fix, but for a completely different use case - we plan to use this library in Big Data/Spark, and that requires TimeZoneEngine to be Serializable, in order not to kill the performance

**Comment by RomanIakovlev** [comment]
I've hit some issue with the publishing process to Maven Central, which must be resolved before I can make a release. If you look at the recent Action runs that run on merge to master, they all fail with some strange error related to "too many redirects". If you have some ideas about how to fix that, it would be much appreciated.

**Comment by SavtechSolutions** [comment]
https://github.com/sbt/sbt-ci-release/issues/173 suggests that this might be due to authorization issues with sonatype, as they disallowed plaintext username/password recently. The thread is as of last week, so might be relevant

**Comment by RomanIakovlev** [comment]
Nice, looks like it helped! Thanks @SavtechSolutions for digging out this info, I appreciate your help.
