### ISSUE TITLE
java.lang.NoSuchMethodError on AWS EMR with commons-compress

### ISSUE THREAD

**Issue by juarezr** [RomanIakovlev/timeshape#16]
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.commons.compress.utils.IOUtils.toByteArray(Ljava/io/InputStream;)[B
	at net.iakovlev.timeshape.TimeZoneEngine.initialize(TimeZoneEngine.java:107)
	at com.ceabs.fleetperformance.base.TimeZoneCommon.initTimeZone(TimeZoneCommon.java:61)

Maybe should upgrade:
// https://mvnrepository.com/artifact/org.apache.commons/commons-compress
compile group: 'org.apache.commons', name: 'commons-compress', version: '1.18'

**Comment by RomanIakovlev** [comment]
Hi, thanks for reporting this. I'll look into this when time allows, or feel free to submit a pull request yourself, and I'll make a SNAPSHOT release to try it out.

**Comment by juarezr** [comment]
For now I solved this issue using [shading](https://imperceptiblethoughts.com/shadow/configuration/relocation/) from gradle:

```
shadowJar {
   relocate 'org.apache.commons.compress', 'shaded.org.apache.commons.compress'
   relocate 'org.tukaani.xz', 'shaded.org.tukaani.xz'
}
```

I have used [geotimezone](https://github.com/bfsmith/GeoTimeZone) before, but it is left unmaintained for a while.
Timeshape coupled with [time4j](http://time4j.net) solved my problems for retrieving local date and time for a given coordinate, even considering daylight savings translations.

Congratulations for the good job done on this library.

**Comment by RomanIakovlev** [comment]
I've just released 2018d.6 that's supposed to fix this issue. Could you please give it a try, and if it helps, close this issue?

**Comment by RomanIakovlev** [comment]
Closing as probably fixed.

**Comment by juarezr** [comment]
I will check with the new version.
Thanks.
