### ISSUE TITLE
Support multiple timezones for single point

### ISSUE THREAD

**Issue by RomanIakovlev** [RomanIakovlev/timeshape#27]
Release 2018f of source data introduces a situation where a single point can be contained by multiple geometries (see https://github.com/evansiroky/timezone-boundary-builder/issues/41). The API of Timeshape must be adjusted to support this.

**Comment by dustin-johnson** [comment]
The new library [TimeZoneMap](https://github.com/dustin-johnson/timezonemap) supports this by adding a new method that returns a list. I opted not to use a QuadTree for searching the time zone regions, as I found it not all that much faster than simple looping through the regions.

**Comment by juarezr** [comment]
There is any plan for making regular releases that just update to the [latest OSM data](https://github.com/evansiroky/timezone-boundary-builder/releases/tag/2018i) versus releases with enhancemnts?

**Comment by RomanIakovlev** [comment]
I've been really busy with my life recently, and this busy period is still ongoing, so that I can't really promise any concrete date for future releases. But maybe you can step in and send a pull request which updates to the latest version of OSM data? I'll prepare a release then.

**Comment by RomanIakovlev** [comment]
Closing this, because release 2019b.7, which has just been published, has support for querying multiple time zones for single geo point.
