### ISSUE TITLE
Please update to database 2018i

### ISSUE THREAD

**Issue by brunocl** [RomanIakovlev/timeshape#32]
Hello,

I am interested to get the new updates available in latest releases of
https://github.com/evansiroky/timezone-boundary-builder/releases

It shows that latest version is 2018i. 
Could you please update TimeShape library with the latest release?

**Comment by RomanIakovlev** [comment]
Hi, I can’t promise any timeline here, but I’d definitely be glad to accept a pull request that updates to the recent data version and validates it’s working fine. I’ll cut a release from it, but otherwise my availability is rather limited.

**Comment by RomanIakovlev** [comment]
Just wanted to let you know I have published the releave 2019b.7 just now, which has the latest available time zone data. Give it a try, and feel free to close the issue if it's not relevant anymore. I have skipped several releases, including 2018i, but it's obsolete now anyway.

**Comment by juarezr** [comment]
Thanks for the release.
