### ISSUE TITLE
Please upgrade protobuf

### ISSUE THREAD

**Issue by crowmagnumb** [RomanIakovlev/timeshape#34]
Version 3.4.0 of protobuf used here gives the following warnings in java 9 and greater...

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.protobuf.UnsafeUtil (file:/home/ken/.m2/repository/com/google/protobuf/protobuf-java/3.4.0/protobuf-java-3.4.0.jar) to field java.nio.Buffer.address
WARNING: Please consider reporting this to the maintainers of com.google.protobuf.UnsafeUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

which I believe is addressed in later versions of protobuf. Cheers.

**Comment by RomanIakovlev** [comment]
Thanks for letting me know, I’ll keep this in mind for the next release.

**Comment by RomanIakovlev** [comment]
I think this issue must be fixed in release 2019b.7, which has just been published. Could you please give it a try and let me know if it works for you now? I have upgraded protobuf version to 3.10.0, which should have this problem fixed.

**Comment by crowmagnumb** [comment]
That seemed to do it. Thank you!

**Comment by RomanIakovlev** [comment]
Thanks for confirmation! Closing the issue now.
