### ISSUE TITLE
timeshape not usable with Java module system

### ISSUE THREAD

**Issue by mipastgt** [RomanIakovlev/timeshape#35]
If you add

    
    <dependency>
        <groupId>net.iakovlev</groupId>
        <artifactId>timeshape</artifactId>
        <version>2018d.6</version>
    </dependency> 

to a project where the library ends up on the java module path (in contrast to the classpath) you will get the following error:

    Error occurred during initialization of boot layer
    java.lang.module.FindException: Unable to derive module descriptor for target/libs/timeshape-2018d.6.jar
    Caused by: java.lang.IllegalArgumentException: timeshape.2018d.6: Invalid module name: '2018d' is not a Java identifier 

In order to fix this problem you would have to remove the 'd' from the version number because this is not allowed. Otherwise your library is not usable with the Java module system.

**Comment by RomanIakovlev** [comment]
Very interesting finding, thanks for reporting it. I’ll consider different versioning scheme if current one is incompatible with JPMS.

**Comment by mipastgt** [comment]
You could also fix this for the time being by just adding this line

    Automatic-Module-Name=net.iakovlev.timeshape

to your manifest file inside the jar. This defines an explicit module name so that it does not have to be derived from the jar file name anymore.

**Comment by RomanIakovlev** [comment]
I think this issue must be fixed in release 2019b.7, which has just been published. Could you please give it a try and let me know if it works for you now? I have applied the fix you've suggested, including the `Automatic-Module-Name` to manifest file.

**Comment by mipastgt** [comment]
It works for me now. Thanks a lot. One more stumbling stone removed on my way to modularize my application.

**Comment by RomanIakovlev** [comment]
Great, thanks for confirmation. Out of curiosity, could you please let me know for what kind of application do you use Timeshape? I'm really interested to learn how people use this library, it gives me motivation to work further on it.

**Comment by mipastgt** [comment]
I use it in a flight planning software to decode the scheduling of NOTAMs.

**Comment by juarezr** [comment]
We use timeshape for calculating local time in trips traveled by cars with a custom IOT sensor/tracker/GPS installed.

Timeshape is a important piece that translate the time in sensor clock ( UTC ) to local time using the GPS coordinates sent by the sensor.

Every day we process all travelled distance/time from 400k cars (expected 1.5M next year) using [Apache Spark](https://spark.apache.org/) running in an [AWS EMR Cluster](https://aws.amazon.com/emr/).

**Comment by RomanIakovlev** [comment]
Thanks for sharing! If you want to, you can list your organizations or projects in the README file of Timeshape (I've just added a placeholder in latest commit https://github.com/RomanIakovlev/timeshape/commit/a2b04c8dc352096baba4bc2fe3e9ce3a0cbedc70). It would be a win-win: I'd appreciate it and your project or company get a little bit more of visibility.

**Comment by RomanIakovlev** [comment]
Anyway, closing this issue now, as the original problem is fixed.
