### ISSUE TITLE
Allow load of external geo data

### ISSUE THREAD

**Issue by tmnd1991** [RomanIakovlev/timeshape#44]
# Scenario

As of now the geo data is shipped with timeshape and that makes the library very desirable since it has no setup needed neither extra dependencies.

# Problem statement

What is a pro for some is a cons for others. Having to update a dependency in a project might not be the easiest way to adapt to timezone changes. The same file that is provided inside the library might be loaded externally (with a dedicated TimeZoneEngine api) to avoid re-deploy of jars upon a timezone change.

**Comment by RomanIakovlev** [comment]
Hi, it is a fair assessment of status quo, and I've been thinking about changing this for some time already. And a big thanks for your PR! I really appreciate you took time to come up with it.

I had a bit of different approach in mind regarding decoupling Timeshape's data from code, but until I come to implement it, I see no reason why we can't use your suggested approach. I'll look deeper into your PR when time will permit, but from the first sight it looks okay. I'll get back to you if any changes will be required.

Thanks again!

**Comment by RomanIakovlev** [comment]
Just wanted to let you know your change was released in Timeshape version 2019b.8 (it's currently on its way to Maven Central). Please have a look at it and feel free to close the issue if it works for you.

**Comment by tmnd1991** [comment]
Thank you very much, I'll try out the new version and come back at you!
