### ISSUE TITLE
remove [DEBUG] messages when starting up timeshape

### ISSUE THREAD

**Issue by gtludwig** [RomanIakovlev/timeshape#51]
Hi all,

I am using timeshape v2019b.8 in my spring-boot application and would like to remove the [DEBUG] messages it spews to the console to signal initialization of the library - which works great, by the way.
I have tried to set a different logging level in application.yml to no success with the following entry:
```
logging:
  level:
    net.iakovlev.timeshape.*: ERROR
```
How can I do so?

**Comment by RomanIakovlev** [comment]
Hi and thanks for your feedback, I appreciate you find Timeshape useful. Unfortunately, I don't know how to configure logging in spring-boot applications. 

What I do know is that current mechanism of changing the log level for Timeshape actually works, at least when Logback is used for logging. The test-app project in this build uses logging, and you can see how it's configured here: https://github.com/RomanIakovlev/timeshape/blob/master/test-app/src/main/resources/logback.xml. If you change the level of the `root` logger, Timeshape output is adjusted accordingly. 

You can also add there something like this into that `logback.xml`:

```
    <logger name="net.iakovlev.timeshape" level="info">
        <appender-ref ref="SDTOUT" />
    </logger>
```
And the result would be that log level of Timeshape is set to info.

But, again, I don't know much about how logging in spring-boot applications works. If you can use Logback for logging in your application, then the approach described above is what you need.

Maybe you could publish a small self-contained example demonstrating this problem? I can check it out, and maybe give you some suggestion.

And by the way, could you please share what kind of application you build using Timeshape? It kind of motivating for me to know how different people use this library.

**Comment by RomanIakovlev** [comment]
Hey @gtludwig, were you able to fix the logging? I'd like to help you with this, but if there isn't anything that must be done in Timeshape, I'd rather close this issue.

**Comment by RomanIakovlev** [comment]
This is probably solved by now, so I'll just go ahead and close this issue.
