### ISSUE TITLE
Empty ZoneId

### ISSUE THREAD

**Issue by PaulDaviesC** [RomanIakovlev/timeshape#52]
Can there be a case where the ZoneId is returned empty by engine.query() for a valid latitude and longitude?

**Comment by RomanIakovlev** [comment]
In general, yes. When the library is initialized with a bounding box smaller than the whole world, all the valid coordinates outside of that bounding box will return the empty answer. When the library is initialized without specifying the bounding box (i.e. for the whole world), it might return the empty answer for some valid coordinates if and only if the source data (see https://github.com/evansiroky/timezone-boundary-builder) has gaps in its coverage at those coordinates.

I'm not sure if the source data covers the whole world without any gaps, but I think the answer is most probably 'yes'. If you must be absolutely sure, ask in the source data project.

**Comment by PaulDaviesC** [comment]
Thanks @RomanIakovlev
