### ISSUE TITLE
Version 2019b.8 depends on geojson-proto 1.1.1-SNAPSHOT, which is not on Maven

### ISSUE THREAD

**Issue by DWvanGeest** [RomanIakovlev/timeshape#54]
https://search.maven.org/artifact/net.iakovlev/timeshape/2019b.8/jar shows a dependency on geojson-proto 1.1.1-SNAPSHOT, which is not found here: https://search.maven.org/artifact/net.iakovlev/geojson-proto

**Comment by RomanIakovlev** [comment]
I have published new version of Timeshape that fixes this problem. The version number is 2019b.9, and it's already synced to Maven Central, give it a try! And thanks again for reporting this.

**Comment by DWvanGeest** [comment]
Yep it's fixed! Thanks for the quick response.
