### ISSUE TITLE
Index.queryPolyline does not return last empty SameZoneSpan

### ISSUE THREAD

**Issue by mikism** [RomanIakovlev/timeshape#63]
Index.queryPolyline() does not account for the case, when one or more points in the end of given polyline are not part of any time zone in the index.
Example of this behavior: `TimeZoneEngine.initialize().queryPolyline(new double[]{54.89, 23.91, 80, 180})` returns a list with only one element:
`new SameZoneSpan(new HashSet<>(Collections.singletonList(ZoneId.of("Europe/Vilnius"))), 1)`.
I would expect (following `TimeZoneEnginePolylineTest.testNonMatchingPoints()` logic) the result to contain one more element:
`new SameZoneSpan(new HashSet<>(), 3)`.
I've added a unit test for such case and a fix: #62 .

**Comment by RomanIakovlev** [comment]
Hello and thanks for your contribution! I need to have a deeper look at it before merging, but on the surface it seems fine.

**Comment by RomanIakovlev** [comment]
Closing the issue since it's fixed in #62 .
