### ISSUE TITLE
source code lack some class;

### ISSUE THREAD

**Issue by iknow34languages** [RomanIakovlev/timeshape#8]
souce code lack the class:net.iakovlev.timeshape.proto.Geojson  

and this source code can not be find in google...

please help to fix it 

thanks;

**Comment by RomanIakovlev** [comment]
This source code is auto-generated from Protobuf definitions in file `core/src/main/protobuf/geojson.proto` during the compilation. To make this happen, you need to compile the project on your computer, and then the source code will be found here: `core/target/src_managed/main/compiled_protobuf/net/iakovlev/timeshape/proto/Geojson.java`.

To compile the project, you need to have the build tool, sbt, installed. You can find info about this in its official website: https://www.scala-sbt.org/. When installed, in terminal window go to the root directory of the Timeshape source code and execute `sbt core/compile`.

**Comment by iknow34languages** [comment]
@RomanIakovlev Thank you very much !
This is a very interesting thing for me .

Thanks
