### ISSUE TITLE
Incorrect ZoneId

### ISSUE THREAD

**Issue by mcculley** [RomanIakovlev/timeshape#89]
I think I have a case where an incorrect ZoneId is returned, but I am not sure.

As a small example, I have two points just east of the Florida coast. One returns America/New_York and the other returns Etc/GMT+5. I am expecting that everything in that general area to return as GMT-4.

Here are examples of points and what they return for me:

```
27.406189, -80.065492: America/New_York
27.405308, -80.016944: Etc/GMT+5
```

Here is my test code:

```
package org.example;

import net.iakovlev.timeshape.TimeZoneEngine;

import java.net.URI;
import java.time.ZoneId;
import java.util.Collection;
import java.util.List;
import java.util.Optional;

public class App {

    private static final TimeZoneEngine tze = TimeZoneEngine.initialize();

    private static Optional<ZoneId> zoneId(final double latitude, final double longitude) {
        return tze.query(latitude, longitude);
    }

    private static Optional<ZoneId> zoneId(final URI geoURI) {
        if (!geoURI.getScheme().equals("geo")) {
            throw new IllegalArgumentException(
                    String.format("unexpected scheme '%s' in '%s'", geoURI.getScheme(), geoURI));
        }

        final String location = geoURI.getSchemeSpecificPart().split(";")[0];
        final String[] coordinates = location.split(",");
        final double latitude = Double.parseDouble(coordinates[0]);
        final double longitude = Double.parseDouble(coordinates[1]);
        return zoneId(latitude, longitude);
    }

    public static void main(final String[] args) {
        final Collection<URI> locations =
                List.of(URI.create("geo:27.405308,-80.016944"), URI.create("geo:37.786971,-122.399677;u=35"),
                        URI.create("geo:27.406189,-80.065492"));
        locations.forEach(l -> System.out.printf("%s: %s\n", l, zoneId(l)));
    }

}
```

I am thinking that maybe the problem is that the point that returns Etc/GMT+5 is just outside of the U.S. boundary and in international waters, but I would still expect it to be in the same daylight savings time regime. I am wondering if I need to handle this as a special case in my code for ocean regions not within a country.

**Comment by rmathar** [comment]
For "international" waters near the Florida Coast (i.e. West of Greenwich) the time zones are Etc/GMT+x, not Etc/GMT-x, because time zone names are constructed compatible with the POSIX-format.

Some more places that are returned with Etc/ specs although they are on Land, not on sea:
(lines in the XEphem format, last number are altitutdes above sea level):

```
Bombay, India                           ;  19  5  3 N   ;  72 51  3 E   ;  -1.0 ; :Etc/GMT-5
Buxton, North Carolina                  ;  35 15 45 N   ;  75 33 40 W   ;   2.0 ; :Etc/GMT+5
Eureka, California                      ;  40 48  8 N   ; 124  9 46 W   ;  13.7 ; :Etc/GMT+8
Galveston, Texas                        ;  29 18 10 N   ;  94 47 43 W   ;   1.5 ; :Etc/GMT+6
KHBI, Saipan, MI                        ;  15  7 20 N   ; 145 41 37 E   ;    -1 ; :Etc/GMT-10
Kensington NSW, Australia               ;  33 52  0 S   ; 151 13  0 E   ;     6 ; :Etc/GMT-10
Long Beach, California                  ;  33 46 14 N   ; 118 11 18 W   ;  10.7 ; :Etc/GMT+8
Macquarie Island, AAT                   ;  54 30  0 S   ; 158 57  0 E   ;    -1 ; :Etc/GMT-11
Portsmouth, New Hampshire               ;  43  4 30 N   ;  70 45 24 W   ;   6.1 ; :Etc/GMT+5
San Diego, California                   ;  32 42 53 N   ; 117  9 21 W   ;   6.1 ; :Etc/GMT+8
Santa Cruz, California                  ;  36 58 18 N   ; 122  1 18 W   ;   6.1 ; :Etc/GMT+8
Sydney NSW, Australia                   ;  33 52  0 S   ; 151 12  0 E   ;    60 ; :Etc/GMT-10
Wilmington, North Carolina              ;  34 14 14 N   ;  77 56 58 W   ;  10.7 ; :Etc/GMT+5
```

**Comment by RomanIakovlev** [comment]
Thanks @rmathar for chiming in. Indeed the timezone designation in the oceans are somewhat confusing, and [many](https://github.com/evansiroky/timezone-boundary-builder/issues/100) [have](https://github.com/evansiroky/timezone-boundary-builder/issues/45) [tripped](https://github.com/evansiroky/timezone-boundary-builder/issues/38) [in the past](https://github.com/RomanIakovlev/timeshape/issues/4#issuecomment-406242101). 

Here's the authoritative quote on the topic: https://github.com/eggert/tz/blob/main/etcetera#L36-L51. 

Does this address your concern @mcculley?

**Comment by rmathar** [comment]
> The boundary of the New-York time zone in the geojson file near Port St Lucie of the Florida coast is shown in https://www.mpia-hd.mpg.de/~mathar/progs/PstLucieTimezone.jpg . The coordinate mentioned is indeed just outside the continental time zone. This is the 2020d file of https://github.com/evansiroky/timezone-boundary-builder/releases , file timezones.geojson.zip unzipped, heavily reduced by removing many time zones, and the "opening" this in https://geojson.io
> 
> For "international" waters near the Florida Coast (i.e. West of Greenwich) the time zones are Etc/GMT+x, not Etc/GMT-x, because time zone names are constructed compatible with the POSIX-format.

From the point of view of this Timeshap code it seems, everything is correct. One may just advice people who are close to shorelines and don't like this to add escape clauses in their client programs which -- whenever they get a time zone ID which starts with Etc --  could start some sort of dithering pattern in wider circles of 100 or 200 miles away from their original point of interest and to check whether they hit on some solid ground there.
