### ISSUE TITLE
Some Questions to ask 

### ISSUE THREAD

**Issue by iknow34languages** [RomanIakovlev/timeshape#9]
This project is very powerful for me;
but i can not very easy to understand it.
So many question in my mind;

  i try to run the main.java in directory:builder\src\main\java\net\iakovlev\timeshape
 i alwasy meet some problem when process the data ;

i have downloaded the timezones.geojson.zip in local directory;
1.why we need build proto or get featureCollection  from the file;
2.The msg coming from geojson  used to download the map data from open street map? or just changeed the data format?
2.it the data have been done from timezoues.geojson.zip 
why not output the file in a good way .. it must filled by customers;

    

> static void writeSevenZProto(String version, String outputPath)  

3.if i failed to buildProto  so i can not run the second steps;

>          TimeZoneEngine engine = TimeZoneEngine.initialize(47.0599, 4.8237, 55.3300, 15.2486);
>         System.out.println(engine.query(52.52, 13.40));

4.    public static TimeZoneEngine initialize(double minlat, double minlon, double maxlat, double maxlon) {
        try (InputStream resourceAsStream = TimeZoneEngine.class.getResourceAsStream("/output.pb.7z");

There is a file output.pb.7z shuld be done by first build step

but i failed to run first step... is there a file that have been processed and be used to query zone directly?

Looking forward your response.

Thanks

**Comment by c-mckenna** [comment]
Hi @iknow34languages,

Are you sure it's necessary to compile yourself? If you want to include this in an existing project it's available in [Maven Central](https://search.maven.org/#artifactdetails%7Cnet.iakovlev%7Ctimeshape%7C2018d.4%7Cjar) to include with a build tool like Maven or Gradle.

Or download the JAR [here](https://search.maven.org/remotecontent?filepath=net/iakovlev/timeshape/2018d.4/timeshape-2018d.4.jar) to work with it manually.

**Comment by RomanIakovlev** [comment]
I'm currently working on automating the artifact creation process and adding documentation about the build structure and overall architecture of Timeshape. This should clarify the questions asked here, so stay tuned. I'll update this issue when I'll merge these changes.

**Comment by RomanIakovlev** [comment]
@iknow34languages I've updated the readme file of this project with description of how this library is designed and built, including many of the questions you've raised in this issue. Particularly, building this project locally is now much easier, because most of the steps were automated, see #13. Please have a look at the updated readme file, and feel free to open a new issue to continue discussion on this topic. I'm closing this issue now.
